baseURL = "http://oraoto.github.io"
DefaultContentLanguage = "en"
title = "Kubernetes By Example"
theme = "beautifulhugo"
metaDataFormat = "yaml"
googleAnalytics = "UA-34425776-2"

[Params]
  subtitle = "Brought to you by the OpenShift team"
  logo = "img/kbe-logo.png"
  favicon = "img/kbe-logo.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = false

[Author]
  name = "Michael Hausenblas"
  github = "mhausenblas"
  twitter = "mhausenblas"

[[menu.main]]
  name = "Try out!"
  url = "diy/"

[[menu.main]]
  name = "Contribute"
  url = "https://github.com/openshift-evangelists/kbe"
